Add support for Ingress Classname in Helm
kubernetes/dashboard pull request #5855
Opened 2021-03-03 02:51 UTC by FrenchBen

Closes #5807 

Adds support for IngressClassName in Helm.

2021-03-03 08:47 UTC, desaintmartin requested changes
Thanks for the contribution! Could you add / edit a test within the ci directory?

2021-03-03 08:47 UTC, desaintmartin commented on aio/deploy/helm-chart/kubernetes-dashboard/README.md
> +`ingress.class.paramers`                        | Ingress Class Parameters                                                                                                         | `[]`
typo! :)

2021-03-03 08:47 UTC, desaintmartin commented on aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
> +  ## All fields must be provided to enable ingressClass support
Maybe point to official doc and state that this requires kube 1.18?

2021-03-22 19:41 UTC, desaintmartin commented
/assign

2021-04-23 04:42 UTC, ftclausen commented
Nice work. Any further movement on this?

2021-04-23 06:25 UTC, desaintmartin commented on aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
> +version: 4.0.3
Could you bumb minor version instead of patch version? According to semver, this is a new feature so we need to bump!

2021-06-30 09:22 UTC, mwipplinger-ftapi commented
Is there any news on when this pull request will be merged? It is quite necessary for our setup to be able to specify the ingressclass

2021-06-30 09:51 UTC, desaintmartin commented
I suggest you could take it over and assign me in a new PR!

2021-08-05 12:11 UTC, desaintmartin commented
closing in favor of https://github.com/kubernetes/dashboard/pull/6299.
/close

2021-08-05 12:11 UTC, closed without merging