Add ability to specify Ingress Classname in Helm
kubernetes/dashboard pull request #6221
Opened 2021-07-01 13:34 UTC by mwipplinger-ftapi

Closes #5807

Adds ability to reference Ingress Class by name in helm.

2021-07-01 14:30 UTC, desaintmartin requested changes
Thanks !

2021-07-01 14:30 UTC, desaintmartin commented on aio/deploy/helm-chart/kubernetes-dashboard/templates/ingress.yaml
> +  {{- if .Values.ingress.class.name }}
It will break since class is not defined by default. To simplify, maybe className? Moreover, using with avoids duplication.

2021-07-01 15:12 UTC, desaintmartin commented
Thanks! You need to signoff you commit (see CLA failed test).

2021-07-01 15:23 UTC, mwipplinger-ftapi commented
> Thanks! You need to signoff you commit (see CLA failed test).

Thank you for the feedback! I am working on the CLA being signed by my company and then me in extention. Hopefully that goes over fast.

2021-07-01 15:54 UTC, mwipplinger-ftapi commented
Signed the CLA. (commenting so the bot rechecks)

2021-07-01 17:49 UTC, desaintmartin approved these changes

2021-07-02 08:14 UTC, mwipplinger-ftapi commented
/lgtm

2021-07-02 08:23 UTC, desaintmartin commented
@floreks could you trigger the CI workflow?

2021-07-05 07:21 UTC, maciaszczykm commented
Re-run triggered.

2021-07-05 08:04 UTC, mwipplinger-ftapi commented
Removed trailing whitespaces. Linting should not fail again.

2021-07-05 13:46 UTC, mwipplinger-ftapi commented
If I interpreted the CI logs correctly then the test failed because the kind cluster didn't manage to provision a node in time which is irrelevant of the code changes and a problem with the test setup itself? Or am I missing something? Is there a way to fix this?

2021-07-09 15:46 UTC, desaintmartin commented
Indeed!
/retest

2021-07-09 15:47 UTC, desaintmartin commented
/assign

2021-07-09 20:17 UTC, Nordie1 commented
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Cédric de Saint Martin ***@***.***>
Sent: Friday, July 9, 2021 10:47 AM
To: kubernetes/dashboard
Cc: Subscribed
Subject: Re: [kubernetes/dashboard] Add ability to specify Ingress Classname in Helm (#6221)


/assign

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/kubernetes/dashboard/pull/6221#issuecomment-877281071>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUYYFL2D5DAUG7PR7N4DWR3TW4KZJANCNFSM47UXUAYA>.

2021-07-14 09:52 UTC, mwipplinger-ftapi commented
/retest

2021-07-15 09:35 UTC, desaintmartin commented
/ok-to-test

2021-07-15 09:35 UTC, desaintmartin commented
/retest

2021-07-15 10:23 UTC, desaintmartin commented
@maciaszczykm could you trigger again? This is quite blocking for reviews...

2021-07-15 11:25 UTC, maciaszczykm commented
Sure, done.

2021-07-15 12:21 UTC, mwipplinger-ftapi commented
Same problem as before, CI fails because kind cluster node times out. Is there something we can do to fix this?

2021-07-18 19:30 UTC, desaintmartin commented
Let's see if https://github.com/kubernetes/dashboard/pull/6264 solves the problem.

2021-07-29 08:05 UTC, desaintmartin commented
It has been merged, could you rebase?

2021-07-29 09:09 UTC, mwipplinger-ftapi commented
I feel like something went wrong with my rebase...I'm sorry that was the first time I did something like that

2021-07-29 09:29 UTC, floreks commented
You can start on a fresh branch and reopen if you'd like.

2021-07-29 09:34 UTC, mwipplinger-ftapi commented
> You can start on a fresh branch and open a new PR if you'd like.

I will do that. Sounds like the best course of action.

2021-07-29 09:48 UTC, closed without merging