Add Restart action to Deployment details page
kubernetes/dashboard pull request #6644
Opened 2021-12-01 08:47 UTC by trentcain

#6639

Backend Changes -
1. Added Restartable to TypeMeta. This is set to true for Deployment resources (similar to Scalable).

Frontend Changes -
1. Added new restart detail action component (ActionbarDetailRestartComponent). The component contains a button with the refresh mat icon, clicking the button shows the restart dialog.
2. Added the Restart action component to the Deployment action bar (ScaleDefaultActionbar). The action is only visible if typeMeta.restartable is true. 
Note for reviewer: I wasn't sure if this action bar should be renamed to something like ScaleRestartDefaultActionbar. Please let me know if this is required, or if this new restart detail action component belongs in a different component.
3. Updated the existing list menu component to use typeMeta.restartable to determine if restart should be enabled in the menu.

Screenshot of new component:
![Screenshot 2021-12-01 183854](https://user-images.githubusercontent.com/53938374/144200923-fc601c9b-f032-487b-a01e-27924e4669ec.png)

2021-12-01 12:10 UTC, maciaszczykm commented
/lgtm

Looks solid.

2021-12-01 12:14 UTC, floreks commented on src/app/frontend/common/components/actionbar/detailactions/restart/template.html
> +        matTooltip="Restart resource"
nit: s/Restart resource/Restart

2021-12-01 12:15 UTC, floreks requested changes
Just a very minor nit pick :slightly_smiling_face: 

This is a really good idea to move this part and control it on the backend side. Code also looks good. Thanks!

2021-12-01 18:55 UTC, trentcain commented
Tooltip updated. Thanks @floreks

2021-12-02 11:13 UTC, maciaszczykm commented
/lgtm

2021-12-02 15:13 UTC, floreks approved these changes

2021-12-02 15:13 UTC, merged