Fixed indent of selector.matchLabels in serviceMonitor
kubernetes/dashboard pull request #6750
Opened 2022-02-02 01:31 UTC by fukuta-tatsuya-intec

An error occurs when activating serviceMonitor as shown below.

```yaml
serviceMonitor:
  enabled: true
```

```bash
$ helm -n rdbox-systems install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard -f values_for_k8s-dashboard.yaml
Error: INSTALLATION FAILED: YAML parse error on kubernetes-dashboard/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key
```
The reason why this error occurs is that the number of indentations in selector.matchLabels is not specified correctly.
I have corrected this number in my PR. Please take care of it.

2022-02-02 01:34 UTC, fukuta-tatsuya-intec commented
/assign @desaintmartin

2022-02-02 06:27 UTC, desaintmartin requested changes
Thanks! Could you bump patch version of the chart?

2022-02-02 06:41 UTC, fukuta-tatsuya-intec commented
Thanks for the review.

This chart is forked based on the following version.

```yaml
version: 5.1.1
appVersion: 2.4.0
```

and Forked from
2d4c06b6ec249df418b2b4891b278ea3f449964f

2022-02-02 07:34 UTC, desaintmartin commented
Yes !

2022-02-02 08:11 UTC, desaintmartin approved these changes
Thanks!

2022-02-02 08:12 UTC, desaintmartin commented
/lgtm

2022-02-02 08:14 UTC, merged

2022-02-21 21:50 UTC, drunkirishcoder commented
I'm using 5.2.0 and still getting this error for some reason.

2022-02-22 09:12 UTC, desaintmartin commented
I am using 5.2.1 and it still does not work.
I've created https://github.com/kubernetes/dashboard/pull/6839 to add testing (and finally fix).