Remove unused import and useless conditional expression
kubernetes/dashboard pull request #6971
Opened 2022-04-06 02:31 UTC by xiaoyang-sde

Remove unused import:
- `MatMenu` in `src/app/frontend/chrome/userpanel/component.ts`
- `MatDialogRef` in `src/app/frontend/common/dialogs/config/dialog.ts`
- `SecurityContext` and `DomSanitizer` in `src/app/frontend/common/pipes/stripansi.ts`
- `StringMap` in `src/app/frontend/resource/cluster/persistentvolume/detail/component.ts`

Remove useless conditional expression:
- `route` in `src/app/frontend/common/components/breadcrumbs/component.ts`

2022-04-06 07:18 UTC, floreks commented on src/app/frontend/common/components/breadcrumbs/component.ts
> +        if (route.data && route.data.parent) {
I think we could simplify this even further and simply go with `route = route?.data?.parent`. An undefined route will break the loop anyway so `else` is not really needed.

2022-04-06 07:20 UTC, floreks requested changes
Overall, I'd prefer to update the `no-unused-vars` linter rule to automatically throw errors when unused imports or variables are found.

2022-04-06 08:22 UTC, xiaoyang-sde commented
> Overall, I'd prefer to update the `no-unused-vars` linter rule to automatically throw errors when unused imports or variables are found.

I found that the .eslintrc.yaml file explicitly disabled this rule for some reason. I could try to enable this rule and check if it will introduce unexpected effects.

2022-04-06 09:40 UTC, floreks commented
Ye, I am not sure why it is disabled. Below config should be sufficient:
`"@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern":  "^_"}],`

2022-04-06 18:13 UTC, xiaoyang-sde commented
> 

Thanks. I enabled it in the latest commit!

2022-04-07 07:05 UTC, maciaszczykm commented
/lgtm
/approve

2022-04-07 07:07 UTC, merged