Update Japanese translation(Line 1594-2887)
kubernetes/dashboard pull request #7079
Opened 2022-05-09 04:18 UTC by ziyi-xie

This PR modifies some translations in the [former PR](https://github.com/kubernetes/dashboard/pull/7054) and updates the Japanese translation from line 1594 to line 2887. Please let me know if there are any mistakes. Thank you !
/hold for Japanese developer's review.
/assign @shu-mutou @atoato88

2022-05-09 05:37 UTC, shu-mutou requested changes

2022-05-09 05:37 UTC, shu-mutou commented on i18n/ja/messages.ja.xlf
> +        <target>で起動</target>
```suggestion
        <target>起動中</target>
```

2022-05-09 05:37 UTC, shu-mutou commented on i18n/ja/messages.ja.xlf
> +        <target>によって制御される</target>
```suggestion
        <target>制御</target>
```
ポッドを制御しているレプリカセットなどを表示するための領域のタイトルですので、名詞が適切です。

2022-05-09 05:37 UTC, shu-mutou commented on i18n/ja/messages.ja.xlf
> +        <target>コマンドを実行</target>
```suggestion
        <target>実行コマンド</target>
```

2022-05-09 05:37 UTC, shu-mutou commented on i18n/ja/messages.ja.xlf
> +        <target>デプロイメントをプレビューする</target>
```suggestion
        <target>デプロイメントのプレビュー</target>
```
これは、フォームのタイトルです。

2022-05-09 06:13 UTC, ziyi-xie commented
@shu-mutou ありがとうございます！修正いたしましたが、エラーが出てきましたので、理由を調べてきます。
また一つ聞きたいことがありまして、上記の英文はdashboardのどこで使われているかは、どうやって確認できるのでしょうか。

2022-05-09 21:26 UTC, atoato88 commented on i18n/ja/messages.ja.xlf
> +        <target>信号</target>
What is the meaning of "Signal" at here?
"Signal" on Linux OS or "Signal" in general word?
"シグナル" (Japanese katakana) may be good if first one.
```suggestion
        <target>シグナル</target>
```

2022-05-10 01:16 UTC, shu-mutou commented
/lgtm
Thanks!

2022-05-10 01:18 UTC, shu-mutou commented
/hold cancel

2022-05-10 01:19 UTC, merged

2022-05-10 01:52 UTC, ziyi-xie commented on i18n/ja/messages.ja.xlf
>            <context context-type="linenumber">29</context>
なるほどです！このgithub上のリポジトリのパスですね。理解できました。ありがとうございます！