ingress paths are now clickable
kubernetes/dashboard pull request #7487
Opened 2022-09-29 13:49 UTC by marcosdiez

This is a copy of #7017
![163737717-08e42793-e9e9-4ba5-b349-4a9390c59af4](https://user-images.githubusercontent.com/297498/193049433-cb8b5d06-6350-401e-a28c-88fbe9e92cfb.png)

-----------

sample YAML to test

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kubernetes-dashboard-lb2
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  defaultBackend:
    service:
      name: test
      port:
        number: 80
  rules:
    - host: dashboard.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
    - host: dashboard2.mydomain.com
      http:
        paths:
          - path: /mypath
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
    - host: dashboard2.mydomain.com
      http:
        paths:
          - path: /mypath/morepath
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
    - http:
        paths:
        - path: /testpath
          pathType: Prefix
          backend:
            service:
              name: test
              port:
                number: 80
    - http:
        paths:
          - path: /icons
            pathType: ImplementationSpecific
            backend:
              resource:
                apiGroup: k8s.example.com
                kind: StorageBucket
                name: icon-assets
    - host: "foo.bar.com"
      http:
        paths:
          - pathType: Prefix
            path: "/bar"
            backend:
              service:
                name: service1
                port:
                  number: 80
    - host: "*.foo.com"
      http:
        paths:
          - pathType: Prefix
            path: "/foo"
            backend:
              service:
                name: service2
                port:
                  number: 80
    - host: foo.bar.com
      http:
        paths:
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: service1
                port:
                  number: 4200
          - path: /bar
            pathType: Prefix
            backend:
              service:
                name: service2
                port:
                  number: 8080
```

2022-09-30 09:10 UTC, maciaszczykm commented on modules/web/src/common/components/ingressrulelist/template.html
> +            <ng-container *ngIf="ingressRuleFlat.host">
Can you merge these two into one `ingressRuleFlat.path.path && ingressRuleFlat.host`?

2022-09-30 09:14 UTC, maciaszczykm commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat?.path?.path }}"
There is no need to use `?.` as `*ngIf` above already checks that. I think it should be in the first changed line.

2022-09-30 09:49 UTC, floreks commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat?.path?.path }}"
I'd actually move this logic to the typescript and use a single method to handle path.

2022-09-30 09:59 UTC, maciaszczykm commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat?.path?.path }}"
Yeah, that would be the best.

2022-09-30 13:46 UTC, marcosdiez commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat?.path?.path }}"
I removed the `?`s.

I considered creating a typescript method (below), but I am not sure we want a method returning raw HTML.

I can change that if you guys prefer, though.

```
  createIngressLink(ingressRuleFlat: IngressRuleFlat): string {
    if (ingressRuleFlat.path.path) {
      if (ingressRuleFlat.host) {
        return '<a href="https://' + ingressRuleFlat.host + ingressRuleFlat.path.path + ' target="_blank">' + ingressRuleFlat.path.path + '</a>';
      } else {
        return ingressRuleFlat.path.path;
      }
    } else {
      return "-";
    }
  }
```

2022-09-30 18:56 UTC, maciaszczykm commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat?.path?.path }}"
Use one method for URL, second for label.

2022-10-03 08:48 UTC, floreks commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat?.path?.path }}"
It could also return a simple wrapper object with label and URL fields.

2022-10-07 10:28 UTC, maciaszczykm commented
@marcosdiez Any updates?

2022-10-09 05:28 UTC, marcosdiez commented
@maciaszczykm ready to merge!

2022-10-10 16:19 UTC, maciaszczykm commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat.path.path }}"
@marcosdiez Fix it please.

2022-10-28 11:51 UTC, maciaszczykm commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat.path.path }}"
@marcosdiez It's not ready. We need to fix that issue.

2022-10-29 09:48 UTC, marcosdiez commented on modules/web/src/common/components/ingressrulelist/template.html
> +              <a href="https://{{ ingressRuleFlat.host }}{{ ingressRuleFlat.path.path }}"
@maciaszczykm I did fix it. Somehow the github UI did not approve update:

![image](https://user-images.githubusercontent.com/297498/198824946-f2a98b6d-ed0f-4ca6-8cc4-15d0380b6149.png)

2022-12-02 08:41 UTC, maciaszczykm reviewed
/lgtm
/approve

2022-12-02 08:47 UTC, maciaszczykm requested changes
> There is no need to use `?.` as `*ngIf` above already checks that. I think it should be in the first changed line.

Actually, wait. 

There should be `?.` in the first `*ngIf`: `ingressRuleFlat?.path?.path`. 

Same for last `*ngIf` you've added: `!ingressRuleFlat?.path?.path`.

Additionally, to simplify syntax you could use switch instead of ifs or move the code to component like @floreks suggested.

/approve cancel

2022-12-02 14:45 UTC, maciaszczykm approved these changes

2022-12-02 14:45 UTC, maciaszczykm commented
/lgtm

2022-12-02 14:45 UTC, merged