WIP: Deployment UI
kubernetes/dashboard pull request #7587
Opened 2023-01-12 21:29 UTC by marcosdiez

closes #7576 

![image](https://user-images.githubusercontent.com/297498/212185122-0fe57950-165c-4fa5-9b93-adadeb9359f3.png)

2023-06-16 03:45 UTC, marcosdiez commented
/remove-lifecycle stale

2023-10-15 10:04 UTC, azro352 requested changes
Add french translations

2023-10-15 10:04 UTC, azro352 commented on modules/web/i18n/fr/messages.fr.xlf
> +        <target state="new">container image</target>
```suggestion
        <target state="new">image du conteneur</target>
```

2023-10-15 10:04 UTC, azro352 commented on modules/web/i18n/fr/messages.fr.xlf
> +        <target state="new">Previous Image Name (click to use)</target>
```suggestion
        <target state="new">Nom de l'image précédente (cliquer pour utiliser)</target>
```

2023-10-15 10:04 UTC, azro352 commented on modules/web/i18n/fr/messages.fr.xlf
> +        <target state="new">Previous Deployment Date</target>
```suggestion
        <target state="new">Date du déploiement précédent</target>
```

2023-10-15 10:04 UTC, azro352 commented on modules/web/i18n/fr/messages.fr.xlf
> +        <target state="new">Set Container Image</target>
```suggestion
        <target state="new">Définir l'image d'un conteneur</target>
```

2023-10-15 10:04 UTC, azro352 commented on modules/web/i18n/fr/messages.fr.xlf
> +        <target state="new">A container image will be replaced on <x id="INTERPOLATION" equiv-text="&quot;\uFFFD0\uFFFD&quot;"/> <x id="INTERPOLATION_1" equiv-text="&quot;\uFFFD1\uFFFD&quot;"/>.</tar
```suggestion
        <target state="new">L'image d'un conteneur sera remplacée sur le <x id="INTERPOLATION" equiv-text="&quot;\uFFFD0\uFFFD&quot;"/> <x id="INTERPOLATION_1" equiv-text="&quot;\uFFFD1\uFFFD&quot;"/>.</target>
```

2024-01-22 11:10 UTC, marcosdiez commented
/remove-lifecycle stale

2024-01-22 11:14 UTC, marcosdiez commented
@maciaszczykm hi. could we merge my PR sometime this year ?

2024-03-26 11:27 UTC, marcosdiez commented
test

2024-08-23 13:07 UTC, closed without merging