feat: add Prometheus labels - `department`, `subDepartment` & `team`
kubernetes/dashboard pull request #7720
Opened 2023-04-28 16:13 UTC by ColdFire87

Hi,

This PR adds labeling support for ServiceMonitor endpoints. Those labels end up on the jobs/targets, and can be used to group jobs. E.g. can add a `department` & `team` label:

```yaml
serviceMonitor:
  enabled: true
  endpoints:
    relabelings:
      - targetLabel: department
        replacement: "Foo"
      - targetLabel: team
        replacement: "Bar"
```

This can then be used in Grafana dashboards to group jobs by labels (or add variables to filter):

```
group by(job) (up{team="Foo"})
```

2023-05-09 11:05 UTC, ColdFire87 commented
/assign @desaintmartin

2023-05-09 11:06 UTC, ColdFire87 commented
@desaintmartin, hey can you please give an estimate of when you could review this?

2023-05-19 13:50 UTC, desaintmartin requested changes
/assign
Thanks!

2023-05-21 14:49 UTC, closed without merging

2023-05-21 14:54 UTC, ColdFire87 commented on charts/helm-chart/kubernetes-dashboard/templates/servicemonitor.yaml
> +      {{- with .Values.prometheus.serviceMonitor.endpoints.relabelings }}
addressed it

2023-05-21 14:56 UTC, ColdFire87 commented
Had to sync changes into my fork, which closed this PR. Opened a new one - https://github.com/kubernetes/dashboard/pull/7749